header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: novatel
child_frame_id: front_6mm
transform:
  translation:
    x: 0.15
    y: 2.3
    z: 0.6
  rotation:
    x: -0.707
    y: 0
    z: 0
    w: 0.707
