child_frame_id: novatel
transform:
  translation:
    x: -0.055
    y: -0.56
    z: 0.32
  rotation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: localization
