header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: localization
transform:
  rotation:
    x: 0
    y: 0
    z: 0.682
    w: 0.731
  translation:
    x: 0.33
    y: 3.56
    z: -0.125
child_frame_id: radar_front_right