header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: localization
transform:
  rotation:
    x: 0
    y: 0
    z: 0.924
    w: -0.383
  translation:
    x: 0.69
    y: -1.0
    z: 0
child_frame_id: sonic11
