header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: localization
transform:
  rotation:
    x: 0
    y: 0
    z: 0
    w: 1
  translation:
    x: -0.265
    y: 3.56
    z: 0
child_frame_id: sonic4
