header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: localization
transform:
  rotation:
    x: 0
    y: 0
    z: 0.383
    w: 0.924
  translation:
    x: -0.685
    y: 3.46
    z: 0
child_frame_id: sonic5
